<a href="https://colab.research.google.com/github/LoniQin/deep_learning_notebooks/blob/master/machine-learning/Iris_DecisionTree_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Iris Decision Tree Classfier

## Import Dependencies

In [6]:
import numpy as np
from sklearn import datasets, model_selection 
%matplotlib inline
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#### The Iris dataset

The [Iris dataset](https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html) consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters. 

#### Load and preprocess the data

First read in the Iris dataset using `datasets.load_iris()`, and split the dataset into training and test sets.

In [2]:
iris_data = datasets.load_iris()
train_data, test_data, train_targets, test_targets = train_test_split(iris_data['data'], iris_data['target'], test_size=0.2)

In [3]:
print(train_data[:10])

[[5.1 3.7 1.5 0.4]
 [5.7 2.8 4.5 1.3]
 [5.  3.4 1.5 0.2]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]
 [4.3 3.  1.1 0.1]
 [4.9 2.5 4.5 1.7]
 [5.2 3.4 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [5.5 4.2 1.4 0.2]]


In [4]:
print(test_targets[:10])

[1 2 1 0 1 1 0 0 0 0]


#### Build and train the Model

In [9]:
model = DecisionTreeClassifier(max_depth=4)
model.fit(train_data, train_targets)
test_accuracy = accuracy_score(test_targets, model.predict(test_data))

## Accuracy

In [10]:

train_accuracy = accuracy_score(train_targets, model.predict(train_data))
print("Train Accuracy:", train_accuracy)
test_accuracy = accuracy_score(test_targets, model.predict(test_data))
print("Test Accuracy:", test_accuracy)

Train Accuracy: 0.9916666666666667
Test Accuracy: 1.0
