<a href="https://colab.research.google.com/github/LoniQin/deep_learning_notebooks/blob/master/machine-learning/KMeans_Iris_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KMeans Iris Classfier

## Import Dependencies

In [11]:
import numpy as np
from sklearn import datasets, model_selection 
%matplotlib inline
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

#### The Iris dataset

The [Iris dataset](https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html) consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters. 

#### Load and preprocess the data

First read in the Iris dataset using `datasets.load_iris()`, and split the dataset into training and test sets.

In [47]:
iris_data = datasets.load_iris()
train_data, test_data, train_targets, test_targets = train_test_split(iris_data['data'], iris_data['target'], test_size=0.2)

In [64]:
print(train_data[:10])

[[5.5 3.5 1.3 0.2]
 [7.2 3.  5.8 1.6]
 [6.3 2.9 5.6 1.8]
 [4.6 3.6 1.  0.2]
 [5.7 3.  4.2 1.2]
 [5.7 4.4 1.5 0.4]
 [5.6 2.7 4.2 1.3]
 [6.4 3.2 4.5 1.5]
 [4.9 2.5 4.5 1.7]
 [7.7 2.6 6.9 2.3]]


In [65]:
print(test_targets[:10])

[1 1 0 1 0 1 2 2 1 0]


#### Build and train the Model
KMeans algorithm is very unstable, so iterate the training loop to search for best model.

In [83]:
best_accuracy = 0.0
best_model = None
for i in range(10):
  model = KMeans(init='random', n_clusters=3, n_init=20, algorithm='elkan')
  model.fit(train_data, train_targets)
  test_accuracy = accuracy_score(test_targets, model.predict(test_data))
  if test_accuracy > best_accuracy:
    best_model = model
    best_accuracy = test_accuracy

## Accuracy

In [84]:
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(train_targets, best_model.predict(train_data))
print("Train Accuracy:", train_accuracy)
test_accuracy = accuracy_score(test_targets, best_model.predict(test_data))
print("Test Accuracy:", test_accuracy)

Train Accuracy: 0.8916666666666667
Test Accuracy: 0.8666666666666667
